<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "portfolio_anal"
 *
 * Auto generated by Extension Builder 2019-01-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PortfolioANAL',
    'description' => 'Portfolio',
    'category' => 'plugin',
    'author' => 'Aurélien SATGER, Nicolas TROCHUT, Adrien CASSAR, Lucas CAUSSAT',
    'author_email' => 'aurelien.satger@etu.u-bordeaux.fr, nicolas.trochut@etu.u-bordeaux.fr, adrien.cassar@etu.u-bordeaux.fr, lucas.caussat@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
